[Interface]
PrivateKey=cEMymGWbYJKt6T5auvofwUsEAXJNONaF1N3lXXMeeWY=
Address=100.64.10.2/24, fde3:4851:7732::2/64
ListenPort=5201

[Peer]
PublicKey=ssxuuZOptjRaTrzq18BTwZvlr7SBK/9VH5L5JVHPQm4=
PresharedKey=icvqwZPZkUiRUuNeeJkUDTtghgFds8Hs+DyWs5DpJeo=
Endpoint=51.159.120.52:5201
AllowedIPs=0.0.0.0/0, ::/0
