// Copyright (c) 2026 Reindert Pelsma
// SPDX-License-Identifier: ISC

package netstackex

import (
	"errors"
	"net/netip"

	"gvisor.dev/gvisor/pkg/buffer"
	"gvisor.dev/gvisor/pkg/tcpip"
	"gvisor.dev/gvisor/pkg/tcpip/adapters/gonet"
	"gvisor.dev/gvisor/pkg/tcpip/header"
	"gvisor.dev/gvisor/pkg/tcpip/stack"
	"gvisor.dev/gvisor/pkg/tcpip/transport/icmp"
	"gvisor.dev/gvisor/pkg/tcpip/transport/tcp"
	"gvisor.dev/gvisor/pkg/tcpip/transport/udp"
	"gvisor.dev/gvisor/pkg/waiter"
)

// SetPromiscuous controls whether the netstack treats packets to unassigned
// destination addresses as local. This is what makes transparent TCP/UDP
// proxying possible for routes such as 0.0.0.0/0.
func (net *Net) SetPromiscuous(enable bool) error {
	if err := net.stack.SetPromiscuousMode(1, enable); err != nil {
		return errors.New(err.String())
	}
	return nil
}

// SetSpoofing controls whether endpoints may bind to addresses not explicitly
// assigned to the NIC. Transparent proxying needs this to reply from the
// original destination address.
func (net *Net) SetSpoofing(enable bool) error {
	if err := net.stack.SetSpoofing(1, enable); err != nil {
		return errors.New(err.String())
	}
	return nil
}

// SetForwarding controls L3 forwarding in the netstack. When enabled, packets
// not addressed to this stack may be routed back out through WireGuard.
func (net *Net) SetForwarding(enable bool) error {
	if net.hasV4 {
		if err := net.stack.SetForwardingDefaultAndAllNICs(header.IPv4ProtocolNumber, enable); err != nil {
			return errors.New(err.String())
		}
	}
	if net.hasV6 {
		if err := net.stack.SetForwardingDefaultAndAllNICs(header.IPv6ProtocolNumber, enable); err != nil {
			return errors.New(err.String())
		}
	}
	return nil
}

// SetTCPReceiveBufferLimit caps the receive buffer advertised by endpoints in
// this stack. This is a process-level guardrail against peers multiplying the
// per-flow TCP receive window into unbounded memory pressure.
func (net *Net) SetTCPReceiveBufferLimit(bytes int) error {
	if bytes <= 0 {
		return nil
	}
	if bytes < tcp.MinBufferSize {
		bytes = tcp.MinBufferSize
	}
	opt := tcpip.TCPReceiveBufferSizeRangeOption{
		Min:     tcp.MinBufferSize,
		Default: bytes,
		Max:     bytes,
	}
	if err := net.stack.SetTransportProtocolOption(tcp.ProtocolNumber, &opt); err != nil {
		return errors.New(err.String())
	}
	return nil
}

// SetPacketFilter installs a filter for packets leaving the netstack toward
// WireGuard. Returning false drops the packet.
func (net *Net) SetPacketFilter(filter func([]byte) bool) {
	net.packetFilter = filter
}

// SetIngressPacketFilter installs a filter for authenticated packets entering
// the netstack from WireGuard. Returning false drops the packet before gVisor
// attempts protocol processing.
func (net *Net) SetIngressPacketFilter(filter func([]byte) bool) {
	net.ingressFilter = filter
}

// InjectOutboundPacket queues a raw IP packet for WireGuard encryption. It is
// used for synthetic control-plane replies, such as ICMP errors generated by
// transparent forwarding policy.
func (net *Net) InjectOutboundPacket(packet []byte) {
	if net.packetFilter != nil && !net.packetFilter(packet) {
		return
	}
	view := buffer.NewViewWithData(packet)
	select {
	case <-net.closed:
		view.Release()
	case net.incomingPacket <- view:
	}
}

// SetTCPForwarder registers a fallback TCP handler for packets that do not
// match a listening endpoint.
func (net *Net) SetTCPForwarder(rcvWnd, maxInFlight int, handler func(*tcp.ForwarderRequest)) {
	if maxInFlight <= 0 {
		maxInFlight = 1024
	}
	forwarder := tcp.NewForwarder(net.stack, rcvWnd, maxInFlight, handler)
	net.stack.SetTransportProtocolHandler(tcp.ProtocolNumber, forwarder.HandlePacket)
}

// SetUDPForwarder registers a fallback UDP handler for packets that do not
// match a listening endpoint.
func (net *Net) SetUDPForwarder(handler func(*udp.ForwarderRequest)) {
	forwarder := udp.NewForwarder(net.stack, handler)
	net.stack.SetTransportProtocolHandler(udp.ProtocolNumber, forwarder.HandlePacket)
}

// SetICMPForwarder registers a fallback handler for ICMP echo traffic that
// does not match a local ping endpoint.
func (net *Net) SetICMPForwarder(handler func(stack.TransportEndpointID, *stack.PacketBuffer) bool) {
	net.stack.SetTransportProtocolHandler(icmp.ProtocolNumber4, handler)
	net.stack.SetTransportProtocolHandler(icmp.ProtocolNumber6, handler)
}

// NewTCPConnFromForwarder turns a gVisor forwarder request into a net.Conn.
func NewTCPConnFromForwarder(r *tcp.ForwarderRequest) (*gonet.TCPConn, error) {
	var wq waiter.Queue
	ep, err := r.CreateEndpoint(&wq)
	if err != nil {
		return nil, errors.New(err.String())
	}
	return gonet.NewTCPConn(&wq, ep), nil
}

// NewUDPConnFromForwarder turns a gVisor UDP forwarder request into a net.Conn.
func NewUDPConnFromForwarder(r *udp.ForwarderRequest) (*gonet.UDPConn, error) {
	var wq waiter.Queue
	ep, err := r.CreateEndpoint(&wq)
	if err != nil {
		return nil, errors.New(err.String())
	}
	return gonet.NewUDPConn(&wq, ep), nil
}

func AddrFromTCPIPAddress(addr tcpip.Address) (netip.Addr, bool) {
	ip, ok := netip.AddrFromSlice(addr.AsSlice())
	if !ok {
		return netip.Addr{}, false
	}
	return ip, true
}

func AddrPortFromEndpointIDLocal(id stack.TransportEndpointID) (netip.AddrPort, bool) {
	ip, ok := AddrFromTCPIPAddress(id.LocalAddress)
	if !ok {
		return netip.AddrPort{}, false
	}
	return netip.AddrPortFrom(ip, id.LocalPort), true
}

func AddrPortFromEndpointIDRemote(id stack.TransportEndpointID) (netip.AddrPort, bool) {
	ip, ok := AddrFromTCPIPAddress(id.RemoteAddress)
	if !ok {
		return netip.AddrPort{}, false
	}
	return netip.AddrPortFrom(ip, id.RemotePort), true
}
